### ISSUE TITLE
"createDB" appears to also be incorrect.

### ISSUE THREAD

**Issue by tebello-thejane** [jfischoff/tmp-postgres#2]
As with the `initDB` issue, `createDB` also appears to be misspelt. At least, it fails for me on Ubuntu, and I can't find any evidence that the capitalisation would work on any other platform.

Assuming that I'm not mistaken about `createDB` never being the correct name, I shall create a PR to change it to `createdb` now.

**Comment by tebello-thejane** [comment]
PR: https://github.com/jfischoff/tmp-postgres/pull/3

**Comment by jfischoff** [comment]
The tests pass on some platform. Either way it should be fixed.
