### ISSUE TITLE
InitDbFailed with no more information

### ISSUE THREAD

**Issue by ocharles** [jfischoff/tmp-postgres#249]
I'm seeing:

```
Exception: InitDbFailed {startErrorStdOut = "", startErrorStdErr = "", startErrorExitCode = ExitFailure 1}
```

This seems rather odd

**Comment by jfischoff** [comment]
If you run with `verboseConfig` it should print out the command and other information that is used for running initdb. 

If you could run with that configuration and post the output here I will attempt to debug the issue.

**Comment by ocharles** [comment]
Ok, from looking at `strace` it seems my `initdb` doesn't support `--no-sync`. I updated to PostgreSQL 11 and all is well! I'm happy to announce the migration from 0.3.0.1 (!) to 1.34.1.0 has otherwise gone smoothly :smiley:

**Comment by ocharles** [comment]
Oh, your message just popped in - I guess that would have been easier. Got there in the end, either way.

**Comment by jfischoff** [comment]
I need to make the 10+ requirement obvious. Sorry about that. 

To support 9 I would need to support `--no-sync`, `--nosync` and not using it all :p
