### ISSUE TITLE
How to change the generated user?

### ISSUE THREAD

**Issue by kozross** [jfischoff/tmp-postgres#261]
The user that gets generated is always the same as the UNIX user. This isn't terribly portable, and I'm unsure how to change it.

**Comment by jfischoff** [comment]
You have to customize the parameters to initdb. The helper [`optionsToDefaultConfig`](https://hackage.haskell.org/package/tmp-postgres-1.34.1.0/docs/Database-Postgres-Temp.html#v:optionsToDefaultConfig) is the easiest way.

The test here has an example: https://github.com/jfischoff/tmp-postgres/blob/master/test/Main.hs#L169

Although I'm sure how clear that example is. You make a `Config` with `optionsToDefaultConfig` and then use it with `withConfig`.
