### ISSUE TITLE
postgres-options source code

### ISSUE THREAD

**Issue by shinzui** [jfischoff/tmp-postgres#275]
I needed to work with the `Options` record to integrate it into my test suite, and it would have been nice to see the source code. I figured it out, but it still would be nice if this package doesn't depend on a package missing its source code. 

There's already an old [issue](https://github.com/jfischoff/postgres-options/issues/3) in the `postgres-options` repo about the missing code.

**Comment by mitchellwrosen** [comment]
hackage is a source distribution - you can download the source code with e.g. `cabal unpack postgres-options-0.2.0.0`

**Comment by shinzui** [comment]
Thanks. I still think it would be nice to have the code on GitHub, but I’ll close the issue to reduce the noise.
