### ISSUE TITLE
Run a script at database init time

### ISSUE THREAD

**Issue by dhess** [jfischoff/tmp-postgres#276]
Hi, thanks for this library! It nicely fills a need we had in our test framework.

We've decided to move our schema management out of Haskell and into [Sqitch](https://sqitch.org). This means we need to run `sqitch deploy` after launching a PostgreSQL instance, but before performing any database operations in our app. We could call `sqitch` directly from our app, but we'd like to keep schema operations separate from application operations for numerous reasons.

Therefore, during testing, we need the ability to run a script between `tmp-postgres`'s `initdb` step and when our test harness runs. We could do that ourselves, but I'm wondering if a) `tmp-postgres` can already do this and I'm just missing something, and b) if not, whether this is something you'd be interested in merging, if we created a PR to support it.

**Comment by dhess** [comment]
Great, thanks for the pointer. I'll look into this and report back here.

**Comment by dhess** [comment]
We've got this all working now. Thanks for this very helpful library!

**Comment by jfischoff** [comment]
Glad to hear. I've unfortunately been busy and haven't been able to update much recently. Let me know though if you run into anything.
