### ISSUE TITLE
Use --no-sync if users have 9.3 and above

### ISSUE THREAD

**Issue by jfischoff** [jfischoff/tmp-postgres#6]
First we should profile to see if --no-sync improves performance when starting up. If it does we should find a way to conditionally use it if users have 9.3 and above.

**Comment by tebello-thejane** [comment]
I was wondering if it is possibly to dynamically guess what version the user is running, and where it is installed.

Basically, by my understanding, `psql` should be available from the path, regardless of whether PG's `bin/` directory has been added to the `PATH`. And one can run the following (at least on Ubuntu):
```
$ psql --version
psql (PostgreSQL) 9.5.7

$ which psql
/usr/lib/postgresql/9.5/bin/psql
```

This way we know what version is installed, and where the `bin/` directory.

Should make things far less painful.

I'll think about it a bit more and present a better-fleshed-out plan.

**Comment by jfischoff** [comment]
I wonder if this should be something it does every run or during installation. I want to be able to keep startup as fast as possible.

**Comment by ocharles** [comment]
Please don't compile in configurations, that's going to come back to bite. Perhaps check once and stick it in a library-global IORef?

**Comment by jfischoff** [comment]
@ocharles I think the easiest thing is just to drop support for 9.2 soon.

**Comment by jfischoff** [comment]
Added the option. No longer supporting older versions of PostgreSQL > 9.3
